consolidated items related to credentials to a single module.
anson-vandoren/esp8266-captive-portal pull request #4
Opened 2020-06-10 06:58 UTC by jasonbrackman

captive_http writes out valid credentials
captive_portal reads/deletes credentials

2020-06-10 13:42 UTC, anson-vandoren requested changes
The rest looks good, thanks!

Calling `self.http_server.set_ip()` needs to be with the SSID of the network we just connected to. `self.essid` is the SSID that the ESP8266 was broadcasting on to display the captive portal.

2020-06-10 13:42 UTC, anson-vandoren commented on captive_portal.py
> +                    self.http_server.set_ip(self.local_ip, self.essid)
This will cause the ESP8266 SSID to be displayed to the user after connection, instead of the newly-connected AP SSID.

2020-06-12 00:36 UTC, anson-vandoren commented on captive_portal.py
> +                    self.http_server.set_ip(self.local_ip, self.essid)
@jasonbrackman I also added a CONTRIBUTORS.md file - feel free to add yourself to that list as well (with or without your GitHub username, or website, or whatever other details you do or don't want to add)

2020-06-12 00:55 UTC, jasonbrackman commented on captive_portal.py
> +                    self.http_server.set_ip(self.local_ip, self.essid)
May take me a day or two -- have a few meetings that are eating into my evening time :).  But will update soon.

2020-06-13 14:05 UTC, merged